<a href="https://colab.research.google.com/github/briandk/2020-virtual-program-in-data-science/blob/master/fastfood_calories.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

from plotnine import *

In [10]:
fast_food = pd.read_csv("https://github.com/briandk/2020-virtual-program-in-data-science/raw/master/data/fastfood_calories.txt")

fast_food = fast_food.drop('Unnamed: 0', axis = 1)
fast_food

    restaurant                                       item  ...  calcium  salad
0    Mcdonalds           Artisan Grilled Chicken Sandwich  ...     20.0  Other
1    Mcdonalds             Single Bacon Smokehouse Burger  ...     20.0  Other
2    Mcdonalds             Double Bacon Smokehouse Burger  ...     50.0  Other
3    Mcdonalds  Grilled Bacon Smokehouse Chicken Sandwich  ...     20.0  Other
4    Mcdonalds   Crispy Bacon Smokehouse Chicken Sandwich  ...     20.0  Other
..         ...                                        ...  ...      ...    ...
510  Taco Bell             Spicy Triple Double Crunchwrap  ...     25.0  Other
511  Taco Bell                Express Taco Salad w/ Chips  ...      NaN  Other
512  Taco Bell                     Fiesta Taco Salad-Beef  ...      NaN  Other
513  Taco Bell                  Fiesta Taco Salad-Chicken  ...      NaN  Other
514  Taco Bell                    Fiesta Taco Salad-Steak  ...      NaN  Other

[515 rows x 17 columns]